# Use postgres/example user/password credentials
version: '3.1'

services:
    db:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: 'ms-user'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3307:3306'
        expose:
            - '3307'
        volumes:
            - microservices-db:/var/lib/mysql


    adminer:
        image: adminer
        restart: always
        depends_on: 
            - db
        ports:
        - 8080:8080

volumes: 
    microservices-db: